---
title: Curriculum Vitae
format:
  html: 
    toc: true
  pdf:
    colorlinks: false
    mainfont: Times New Roman
    include-in-header:
          text: |
            \usepackage[lmargin = 0.7in,rmargin = 0.7in,
            tmargin =0.9in, bmargin = 0.9in]{geometry}
            \usepackage{fancyhdr}
            \pagestyle{fancy}
            
            \fancyhf{}
            \rhead{\thepage}
            \lhead{Nina Galanter}
            
            \makeatletter         
            \renewcommand\maketitle{
            \begin{center}
            {\Large \textbf{Nina Galanter}}\\
            \vspace{1mm}
            \normalsize galantn@mskcc.org\\
            \vspace{1mm}
            Updated January 2026
            \end{center}} 
            \makeatother
         
            \addtokomafont{disposition}{\rmfamily}
format-links: [pdf]
---

## EDUCATION

| **Ph.D., Biostatistics, June 2025**
| University of Washington, Seattle, WA
| Dissertation: Topics in Causal Inference for Individualized Treatment
| Advisors: Marco Carone and Alex Luedtke
|
| **B.A., Mathematics, May 2018**
| Grinnell College, Grinnell, IA

## RESEARCH EXPERIENCE

### GRADUATE STUDENT RESEARCHER

| **Topics in causal inference for individualized treatment (Dissertation)** 
| Department of Biostatistics, University of Washington, Seattle, WA 
| September 2020 -- June 2025, Advisors: Marco Carone and Alex Luedtke
|  
-   First project involved bounding the benefit of an optimal treatment rule using summary statistics. Results published and R package implementing method is on GitHub.

-   Second two projects involved methods for estimation and inference for optimal treatment rules considering a primary outcome and a risk outcome. Methods incorporate machine learning. Manuscript and R package are in preparation.

-   Primary application is medication treatment for depression using electronic health records.

| **Improving communication about serious illness – hospital study**  
| Department of Biostatistics, University of Washington, Seattle, WA 
| September 2024 -- June 2025, Supervisor: Lyndia Brumback, Ph.D.
|
-   Conducted the statistical analysis for the clinical trial for an intervention to facilitate goals-of-care discussions between patients and providers in a hospital critical care setting.

-   Outcomes of interest, from electronic health record and survey data, included natural language processing-derived outcomes, intensity of care outcomes, and patient-reported outcomes.

| **Pediatric vaccination in pharmacies and well-child visits** 
| Comparative Health Outcomes, Policy, and Economics Institute, University of Washington, Seattle, WA 
| June 2023 -- January 2025
|
- Contributed to the statistical analysis plan and edited the manuscript, now published, for a retrospective cohort study using health care claims data.

| **RSV correlates of protection in hematopoietic transplant recipients** 
| Vaccine and Infectious Disease Division, Fred Hutch Cancer Research Center, Seattle, WA 
| June 2023 -- June 2025, Principal Investigator: Jim Boonyaratanakornkit, Ph.D.
|
-   In collaboration with research team, created a statistical analysis plan, conducted the analysis, and contributed to the manuscript for a time-to-event analysis of an observational cohort.

| **Ranking tailoring variables for constructing treatment rules** 
| Kaiser Permanente Washington Health Research Institute, Seattle, WA 
| March 2020 -- September 2024, Supervisor: Susan Shortreed, Ph.D.
|
-   Multiple projects about using marginal structural models to estimate optimal treatment rules and their values. One paper published and another manuscript submitted.

-   Methods applied to clinical trial data and electronic health records data.

### CONSULTING

| **Statistical Consultant** 
| Department of Biostatistics, University of Washington, Seattle, WA 
| January 2022 -- March 2022, Supervisors: Katie Kerr, Ph.D., and Tamre Cardoso, Ph.D
|
-   Led and participated in hour-long consulting sessions for researchers across the University of Washington on topics including study design, analysis plan, and implementation in R.

-   With another student, created and implemented an analysis plan and wrote a report about the association between receiving a left ventricular assist device and time to heart transplant.

### UNDERGRADUATE STUDENT RESEARCHER

| **Efficient communication in distributed machine learning** 
| Institute for Pure and Applied Mathematics RIPS Program, Hong Kong 
| June 2017 -- August 2017, Supervisor: Albert Ku, Ph.D.<br>
|
| **Machine learning for the classification of toxicological effects** 
| Department of Mathematics, North Carolina State University, Raleigh, NC 
| May 2016 -- August 2016, Supervisor: Hien Tran, Ph.D.<br>
|
| **Evolutionary biology and game theory: the territorial raider game** 
| Mathematics and Statistics Dept., University of North Carolina Greensboro, Greensboro, NC 
| May 2015 -- July 2015, Supervisor: Jan Rychtář, Ph.D.

## PUBLICATIONS

### Statistical Methods

**Galanter, N.** , Carone, M., Kessler, R.C., Luedtke, A. (2024). [Can the potential benefit of individualizing treatment be assessed using trial summary statistics alone?](https://doi.org/10.1093/aje/kwae040) *American Journal of Epidemiology*.

Wu, J., **Galanter, N.** , Shortreed, S. M., Moodie, E. E. M. (2022). [Ranking tailoring variables for constructing individualized treatment rules: an application to schizophrenia](https://rss.onlinelibrary.wiley.com/doi/10.1111/rssc.12533). *Journal of the Royal Statistical Society: Series C*.

### Public Health and Medicine

Pernikoff, S., Clurman, A., Rötepohl, M., **Galanter, N.**, Bibby, M., Harris, E., Stevens-Ayers, T., Xie, H., Ueda Oshima, M, Cheng, G.S, Englund, J.A.,Boeckh, M.J., Boonyaratanakornkit, J. (2026, January). [Respiratory Syncytial Virus in Hematopoietic Cell Transplant Recipients: Clinical and Humoral Risk Factors for Infection.](https://doi.org/10.1093/ofid/ofag005) *Open Forum Infectious Diseases* 

Bhardwaj, S., **Galanter, N.** , Berenbrok, L.A., Shah P.D, Bacci, J.L. (2025). [Pediatric Vaccination in Pharmacies is not Associated with Delayed Well-Child Visits Among Commercially Insured Children](https://doi.org/10.1093/haschl/qxaf028). *Health Affairs Scholar*.

### Other

**Galanter, N.** , Silva, D., Jr., & Rowell, J., Rychtář, J. (2017). [Resource Competition Amid Overlapping Territories: The Territorial Raider Model Applied to Multi-Group Interactions](http://dx.doi.org/10.1016/j.jtbi.2016.10.007). *Journal of Theoretical Biology.*

**Galanter, N.** , Silva, D., Jr., Rychtář, J., & Rowell, J. (2016). [The Territorial Raider Game and Graph Derangements](http://dx.doi.org/10.1016/j.dam.2016.03.016). *Discrete Applied Mathematics*.

## TEACHING EXPERIENCE

### INSTRUCTOR

| **Data Analysis and Reporting (Co-instructor)** 
| University of Washington, Spring 2025 
|
  - Graduate-level course on conducting data analyses. Using real data examples, students practiced writing statistical analysis plans, conducting analyses, assessing limitations and assumptions, and reporting results.  
  
  - Revised course in collaboration with faculty co-instructor, facilitated in-class discussions, gave lectures, and graded.
  
| **Regression Methods in the Health Sciences** 
| University of Washington, Spring 2023 
|
  - Intermediate undergraduate course including linear, logistic, and Cox regression. Students used R language.
  
  - Responsible for curriculum and all course materials, including lectures, quizzes, R labs, and data analysis project.
  
  - Implemented a specifications-based grading system.
  
### MENTOR 

| **University of Washington Statistics Directed Reading Program** 
| Winter 2025 Topic: Target Trial Framework for Causal Inference    
| Winter and Fall 2023 Topic: Survival Analysis      
| Winter and Spring 2022 Topic: Optimal Treatment Rules  
|
  - One-on-one mentoring of undergraduates culminating in a final report and presentation. Created the concept and curriculum for each project.

### TEACHING ASSISTANT

| **Statistical Inference for Biometry II** 
| University of Washington, Winter 2024 
|
  - Held weekly office hours, refined solution keys, created rubrics for and graded homeworks and exams, and answered student questions via email and the course discussion board.

| **Categorical Data Analysis in Epidemiology** 
| University of Washington, Fall 2024 
| 
  - Created discussion section materials, ran discussion sections, held office hours, edited exams, and graded for a categorical data analysis course for graduate students in the health sciences.

| **Introduction to Survival Analysis** 
| University of Washington Summer Institutes, Summer 2024 
|  
  - Answered questions during lectures and via the course Slack for an online short course on survival analysis for professionals in public health and medicine. 

| **Survival Data Analysis in Epidemiology** 
| University of Washington, Winter 2023 
|  
  - Created discussion section materials, ran discussion sections, held office hours, created rubrics, and graded for a categorical data analysis course for graduate students in the health sciences.

| **Biostatistics for the Health Sciences** 
| University of Washington, Winter 2022, Winter 2020, Fall 2019
|      
  - Created discussion section materials, ran discussion sections, held office hours, and graded for an introductory undergraduate biostatistics course.

### OTHER 

| **Grader, Introduction to Data Science** 
| Grinnell College, Spring 2018 
|
| **Grader, Statistical Modeling** 
| Grinnell College, Fall 2017
|
| **Course Mentor, Applied Statistics** 
| Grinnell College, Fall 2015


## HONORS AND AWARDS

| **University of Washington**
| National Science Foundation Graduate Research Fellowship, March 2021 
| Department of Biostatistics Merit Award, April 2019 
| ARCS Foundation Scholar, April 2019
|
| **Grinnell College**
| Grinnell College Linn Smith Prize in Mathematics, April 2018 
| Honors in Mathematics, May 2018 
| Phi Beta Kappa Member, April 2017 
| Goldwater Scholarship, March 2017 
| Grinnell College Pamela Ferguson Prize in Mathematics, February 2017 
| Phi Beta Kappa Beta Chapter of Iowa Sophomore Book Award, April 2016 

## PRESENTATIONS AND POSTERS

### PRESENTATIONS

| **Inference for Optimal Treatment Rules under Stratum-wise Constraints for Discrete Rules** 
| WNAR Annual Meeting, Fort Collins, CO, June 11, 2024 
| Joint Statistics Meetings, Toronto, ON, August 10, 2023 
| University of Washington Biostatistics Student Seminar, Seattle, WA, February 15, 2023 
|
| **Variable Selection for Estimation of Interpretable Treatment Rules under Confounding** 
| University of Washington Biostatistics Student Seminar, Seattle, WA, November 2, 2022 
|
| **Can the potential benefit of individualizing treatment be assessed using trial summary statistics alone?** 
| Joint Statistics Meetings, Washington DC, August 9, 2022 
| University of Washington Biostatistics Student Seminar, Seattle, WA, February 2, 2022 
|
| **Efficient Communication in Distributed Machine Learning** 
| Nebraska Conf. for Undergraduate Women in Mathematics, Lincoln, NE, January 27, 2018 
| Grinnell Mathematics and Statistics Student Seminars, Grinnell, IA, February 6, 2018 

::: {.content-hidden when-format="html"}
\pagebreak 
:::


| **Machine Learning for the Classification of Toxicological Effects** 
| Grinnell Mathematics and Statistics Student Seminars, Grinnell, IA, September 14, 2016
| Joint Mathematics Meetings, Atlanta, GA, January 7, 2017
|
| **Machine Learning, Nash Equilibria, and Derangements: The Territorial Raider Game** 
| Grinnell Mathematics and Statistics Student Seminars, Grinnell, IA, October 6, 2015 
| UNCG Regional Mathematics and Statistics Conference, Greensboro, NC, November 7, 2015 
| Joint Mathematics Meetings, Seattle, WA, January 8, 2016 
| Nebraska Conf. for Undergraduate Women in Mathematics, Lincoln, NE, January 31, 2016

### POSTERS

| **Efficient Communication in Distributed Machine Learning** 
| Joint Mathematics Meetings, San Diego, CA, January 12, 2018
|
| **The Territorial Raider Model with Strategic Movement and Multi-Group Interactions** 
| Intl. Symposium on Biomath. and Ecology Edu. and Research, Normal, IL, October 9, 2015 
| Joint Mathematics Meetings, Seattle, WA, January 8, 2016

## PROFESSIONAL SERVICE

### University of Washington  

Member, Biostatistics Curriculum Committee, September 2023 -- June 2025

Member, Biostatistics Equity, Diversity, and Inclusion Committee, September 2019 -- June 2025

Member, Biostatistics Activities and Events Squad, February 2019 -- June 2025

Facilitator, Biostatistics Student Seminar, September 2022 -- June 2024

Facilitator, Statistical Education Reading Group, January 2022 -- June 2023

Co-leader, Statisticians and Biostatisticians of Underrepresented Genders, October 2020 -- June 2023

Member, Admissions Committee, September 2022 -- March 2023

Senator, Graduate and Professional Student Senate, September 2019 -- June 2020; September 2021 -- June 2022

### Grinnell College
      
President, Mathematics Student Educational Policy Committee, August 2017 -- May 2018

Member, Mathematics Student Educational Policy Committee, August 2016 -- December 2016 

### Reviewer  
| Biometrics 
| Journal of the Royal Statistical Society Series C

<br>
<br>

::: {.content-hidden when-format="pdf"}
HTML/PDF formatting option inspired by [this page](https://www.cynthiahqy.com/posts/cv-html-pdf/). 
:::
