---
title: Publications
---

### Statistical Methods

**Galanter, N.** , Carone, M., Kessler, R.C., Luedtke, A. (2024). [Can the potential benefit of individualizing treatment be assessed using trial summary statistics alone?](https://doi.org/10.1093/aje/kwae040) *American Journal of Epidemiology*.

Wu, J., **Galanter, N.** , Shortreed, S. M., Moodie, E. E. M. (2022). [Ranking tailoring variables for constructing individualized treatment rules: an application to schizophrenia](https://rss.onlinelibrary.wiley.com/doi/10.1111/rssc.12533). *Journal of the Royal Statistical Society: Series C*.

### Public Health and Medicine

Pernikoff, S., Clurman, A., Rötepohl, M., **Galanter, N.**, Bibby, M., Harris, E., Stevens-Ayers, T., Xie, H., Ueda Oshima, M, Cheng, G.S, Englund, J.A.,Boeckh, M.J., Boonyaratanakornkit, J. (2026, January). [Respiratory Syncytial Virus in Hematopoietic Cell Transplant Recipients: Clinical and Humoral Risk Factors for Infection.](https://doi.org/10.1093/ofid/ofag005) *Open Forum Infectious Diseases* 

Bhardwaj, S., **Galanter, N.** , Berenbrok, L.A., Shah P.D, Bacci, J.L. (2025). [Pediatric Vaccination in Pharmacies is not Associated with Delayed Well-Child Visits Among Commercially Insured Children](https://doi.org/10.1093/haschl/qxaf028). *Health Affairs Scholar*.

### Other

**Galanter, N.** , Silva, D., Jr., & Rowell, J., Rychtář, J. (2017). [Resource Competition Amid Overlapping Territories: The Territorial Raider Model Applied to Multi-Group Interactions](http://dx.doi.org/10.1016/j.jtbi.2016.10.007). *Journal of Theoretical Biology.*

**Galanter, N.** , Silva, D., Jr., Rychtář, J., & Rowell, J. (2016). [The Territorial Raider Game and Graph Derangements](http://dx.doi.org/10.1016/j.dam.2016.03.016). *Discrete Applied Mathematics*.